# MPPI parameters
dt: 0.01 # time step
n_samples: 100 # number of samples
lambda: 0.001 # temperature
horizon: 40 # horizon
n_workers: 4 # number of workers
seed: 42 # seed

# model parameters for contact model
o_solref:
  - 0.02 # time constant for contact model
  - 1.0  # damping ratio for contact model

# spline parameters
sample_type: "cubic" # spline order 
n_knots: 4 # number of knots

# noise to perturb the control inputs
noise_sigma:
  - 0.03 # FR_1
  - 0.05 # FR_2
  - 0.09 # FR_3
  - 0.03 # FL_1
  - 0.05 # FL_2
  - 0.09 # FL_3
  - 0.03 # RR_1
  - 0.05 # RR_2
  - 0.09 # RR_3
  - 0.03 # RL_1
  - 0.05 # RL_2
  - 0.09 # RL_3


# diagonal entries of the cost matrix Q
Q_diag: 
  - 1000 # x
  - 1000 # y
  - 600 # z
  - 1000000 # rot_quat
  - 1000000 # rot_quat
  - 1000000 # rot_quat
  - 1000000 # rot_quat
  - 300 # FR_1
  - 300 # FR_2
  - 300 # FR_3
  - 300 # FL_1
  - 300 # FL_2
  - 300 # FL_3
  - 300 # RR_1
  - 300 # RR_2
  - 300 # RR_3
  - 300 # RL_1
  - 300 # RL_2
  - 300 # RL_3
  - 0.05 # x_dot
  - 0.05 # y_dot
  - 0.05 # z_dot
  - 0.05 # rot_x_dot
  - 0.05 # rot_y_dot
  - 0.05 # rot_z_dot
  - 0.05 # FR_1_dot
  - 0.05 # FR_2_dot
  - 0.05 # FR_3_dot
  - 0.05 # FL_1_dot
  - 0.05 # FL_2_dot
  - 0.05 # FL_3_dot
  - 0.05 # RR_1_dot
  - 0.05 # RR_2_dot
  - 0.05 # RR_3_dot
  - 0.05 # RL_1_dot
  - 0.05 # RL_2_dot
  - 0.05 # RL_3_dot

# diagonal entries of the cost matrix R
R_diag:
  - 0.01 # FR_1
  - 0.01 # FR_2
  - 0.01 # FR_3
  - 0.01 # FL_1
  - 0.01 # FL_2
  - 0.01 # FL_3
  - 0.01 # RR_1
  - 0.01 # RR_2
  - 0.01 # RR_3
  - 0.01 # RL_1
  - 0.01 # RL_2
  - 0.01 # RL_3

q_ref:
  - 0.0 # x
  - 0.0 # y
  - 0.27 # z
  - 1.0 # quat 0
  - 0.0 # quat 1
  - 0.0 # quat 2
  - 0.0 # quat 3
  - 0.0 # FR_1
  - 0.9 # FR_2
  - -1.8 # FR_3
  - 0.0 # FL_1
  - 0.9 # FL_2
  - -1.8 # FL_3
  - 0.0 # RR_1
  - 0.9 # RR_2
  - -1.8 # RR_3
  - 0.0 # RL_1
  - 0.9 # RL_2
  - -1.8 # RL_3

v_ref:
  - 0.0 # x_dot
  - 0.0 # y_dot
  - 0.0 # z_dot
  - 0.0 # rot_x_dot
  - 0.0 # rot_y_dot
  - 0.0 # rot_z_dot
  - 0.0 # FR_1_dot
  - 0.0 # FR_2_dot
  - 0.0 # FR_3_dot
  - 0.0 # FL_1_dot
  - 0.0 # FL_2_dot
  - 0.0 # FL_3_dot
  - 0.0 # RR_1_dot
  - 0.0 # RR_2_dot
  - 0.0 # RR_3_dot
  - 0.0 # RL_1_dot
  - 0.0 # RL_2_dot
  - 0.0 # RL_3_dot
  